export const reset = '\x1b[0m'
export const underscore = '\x1b[4m'
export const red = '\x1b[31m'
export const green = '\x1b[32m'
export const magenta = '\x1b[35m'
export const cyan = '\x1b[36m'

export const images = [
    'baked-ziti.jpg',
    'beef-enchilada-casserole.jpg',
    'birria-tacos.jpg',
    'black-bean-smash-burgers.jpg',
    'bolognese-sauce.jpg',
    'butter-chicken.jpg',
    'california-rolls.jpg',
    'chicken-tikka-masala.jpg',
    'chicken-tortilla-soup.jpg',
    'cilantro-lime-rice.jpg',
    'fettuccine-alfredo-with-mushrooms.jpg',
    'fresh-basil-pesto.jpg',
    'ginger-beef-stir-fry.jpg',
    'greek-chicken-skewers-with-yogurt-sauce-chicken-souvlaki.jpg',
    'greek-salad.jpg',
    'homemade-pizza.jpg',
    'indian-style-rice.jpg',
    'instant-pot-mexican-pulled-pork.jpg',
    'kung-pao-chicken.jpg',
    'long-island-iced-tea.jpg',
    'michelada.jpg',
    'naan-bread.jpg',
    'orange-chicken.jpg',
    'paccheri-with-quick-sausage-ragu.jpg',
    'pad-thai.jpg',
    'pasta-carbonara.jpg',
    'peach-bellini-cocktails.jpg',
    'peach-margarita.jpg',
    'red-curry-poached-salmon.jpg',
    'salsa-verde-chicken-enchiladas.jpg',
    'shrimp-fried-rice.jpg',
    'skillet-eggplant-parmesan.jpg',
    'slow-cooker-honey-chipotle-chicken-tacos.jpg',
    'taquitos-de-pollo.jpg',
    'tepache.jpg',
    'thai-green-curry.jpg',
    'thai-iced-tea-cha-yen.jpg',
    'vegetable-fried-rice.jpg',
    'watermelon-lemonade.jpg',
]

export const categories = [
    { name: 'Breakfast' },
    { name: 'Brunch' },
    { name: 'Lunch' },
    { name: 'Dinner' },
    { name: 'Appetizer' },
    { name: 'Dessert' },
    { name: 'Drink' },
    { name: 'Snack' },
    { name: 'Soup' },
    { name: 'Weeknight' },
    { name: 'Beef' },
    { name: 'Pork' },
    { name: 'Chicken' },
    { name: 'Pasta' },
    { name: 'Seafood' },
    { name: 'Turkey' },
    { name: 'Vegetarian' },
    { name: 'Baking' },
    { name: 'Grill' },
    { name: 'Instant Pot' },
    { name: 'Slow Cooker' },
]

export const cuisines = [
    { name: 'American' },
    { name: 'Chinese' },
    { name: 'French' },
    { name: 'Fusion' },
    { name: 'Greek' },
    { name: 'Indian' },
    { name: 'Italian' },
    { name: 'Japanese' },
    { name: 'Korean' },
    { name: 'Mexican' },
    { name: 'Middle Eastern' },
    { name: 'Thai' },
    { name: 'West African' },
]
